[project]
name = "hw5"
version = "0.1.0"
description = "Tasks for homework5 Python HSE"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "aiofiles>=24.1.0",
    "aiohttp>=3.11.16",
]
